### ISSUE TITLE
Procedural Macros are missing in book

### ISSUE THREAD

**Issue by Feliix42** [iolivia/rust-sokoban#57]
I'm just reading the book and I noticed that the procedural macros in [Chapter 1, Section 3](https://sokoban.iolivia.me/c01-03-entities-components.html) are missing, because they are treated as comments due to the leading `#`.

This makes following this specific section a little hard as the text explains procedural macros, yet there are none in the code of the whole section. So it may be a good idea to either explain the macro annotations outside the snippet or alter the snippet (which may be not that easy as it is imported from the source file itself)?

Anyway, it's been a fun book so far, even for a long-time Rustacean, so thanks!

**Comment by iolivia** [comment]
hey thanks a lot for the issue, it was totally a bug, not intended. I think it was to do with the mdbook version used to deploy the book, I bumped it up and it looks good to me now, have a look and please re-open if it's still not fixed (might need a ctrl + shift + r to hard refresh just in case it's cached). 

glad to hear you are enjoying 🚀
