### ISSUE TITLE
Component traits missing from chapter 3

### ISSUE THREAD

**Issue by trojanfoe** [iolivia/rust-sokoban#58]
Hi, really enjoying your tutorial series, however you mention you will be using traits like `VecStorage` in chapter 3 but don't actually show them in the code and as it stands it won't compile.

Or is it intended that people look at the code in git repo or read the `specs` docs instead?

**Comment by iolivia** [comment]
hey! thanks! and sorry about that, I think it was an issue with the mdbook version used at deployment time as it looked good locally for me, I bumped the version and it looks good now, please re-open if it's still not fixed (also might need to do a hard refresh).
