### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by iolivia** [iolivia/rust-sokoban#60]
Opening this as the master tracker issue for translations. 

There are three main things to be tackled:
1. adding infrastructure to support translations - this is very dependent on mdbook and currently complicated - see https://github.com/rust-lang/mdBook/issues/5 
2. writing translations - once the infrastructure is in place we can start working on actual translations, which languages and how much depends on interest and contributors who speak different languages
3. coming up with a process for managing changes across languages - if we add new chapters, what does that mean for translations? do we say that english is the base, and translations might be a few diffs off? 

Also, if you come to this issue interested in a specific translation or would like to contribute by translating, leave a comment below including the language so we can keep track of interest, etc.

**Comment by TianLangStudio** [comment]
Chinese 
Hi! I am [Tianlang2](https://twitter.com/TianLang2) .

**Comment by iolivia** [comment]
hey @TianLangStudio, thanks for the interest. I'll take a look at how to structure the translations and get back to you, then you can start with the translation whenever you have time 😄

**Comment by TianLangStudio** [comment]
Ok.  Maybe I can translate the file README.md to Chinese first by adding a file named README-zh_CN.md

**Comment by iolivia** [comment]
ok so I've looked into, mdbook doesn't have support for translations and I don't think it's worth using a custom fork for this. I think we should just have a separate folder for each translation (ideally sharing the assets used in the book and definitely pointing to the same code samples), and do some magic on the CI to publish each translation separately, maybe the english version can stay at the root and we can publish let's say chinese to /ch or something like that. 

in terms of process for new translations, I'd say we'd need at least the first chapter translated in a language to publish that specific translation (if we wait for everything to be translated we might never do it, it also gives people a chance to contribute if they want to translate further). in terms for keeping them in sync with english, if we make changes to the english text we can make a note in a specific translation issue to keep track of what needs to be re-translated.

**Comment by TianLangStudio** [comment]
Good job! Maybe create a direction named `src/zh_CN` for  Simplified Chinese.   And somebody who is come from Taiwan makes `src/zh_TW`,  Maybe.   
If we make a good start, it's easy for others to get started.

**Comment by mgeisler** [comment]
Hi there, I just wanted to mention that I ran into the same problem... I wrote a couple of mdbook plugins to help me with translating a mdbook project: https://github.com/google/mdbook-i18n-helpers. Maybe they will be useful for you too :slightly_smiling_face:
