### ISSUE TITLE
use `sort_by_key` to improve readabilty

### ISSUE THREAD

**Issue by hellow554** [iolivia/rust-sokoban#66]
https://github.com/iolivia/rust-sokoban/blob/5e1ac13664d739c21af680fa7fa63b690f53aa92/code/rust-sokoban-c01-04/src/main.rs#L65

At first I thought: you could just use `cmp` instead of `partial_cmp.unwrap` but then at the second look, why don't you just use [`sort_by_key`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_key) (or better `sort_unstable_key_by` which will improve performance for large slices because of the underlying sorting algorithmn)

**Comment by iolivia** [comment]
great suggestion, thank you @hellow554!
