### ISSUE TITLE
Chapter 2 Section 5 Missing code

### ISSUE THREAD

**Issue by timw4mail** [iolivia/rust-sokoban#68]
Attempting to just follow along, there are two missing code pieces in the book for the Gameplay section:

Incrementing the move count in the input system:
```rust
        // We've just moved, so let's increase the number of moves
        if to_move.len() > 0 {
            gameplay.moves_count += 1;
        }
```

And running the new system:
```rust
        // Run gameplay state system
        {
            let mut gss = GameplayStateSystem {};
            gss.run_now(&self.world);
        }
```

It took me a while to track down the changes in the full code.

**Comment by iolivia** [comment]
hey @timw4mail, thanks for flagging this! should be fixed shortly in the PR above.
