### ISSUE TITLE
[Translation] zh_CN 

### ISSUE THREAD

**Issue by iolivia** [iolivia/rust-sokoban#83]
- [x] Summary
- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3

**Comment by iolivia** [comment]
@TianLangStudio I started the infrastructure for book translations, see a preview at https://unruffled-kowalevski-2fc66b.netlify.app/zh_cn/. Do you think you can translate the SUMMARY.md as well so the chapter names are in the right language as well? 😄

**Comment by TianLangStudio** [comment]
Got it.
I'm happy to do it.

**Comment by iolivia** [comment]
translations are done, waiting for PR fixes from @TianLangStudio before merging. thank you @TianLangStudio 🙏

**Comment by iolivia** [comment]
fixed in #98
