### ISSUE TITLE
Not working with GNOME 3.38 + Wayland 1.19

### ISSUE THREAD

**Issue by mister-spock** [iolivia/rust-sokoban#93]
The GGEZ engine cannot create a window in said environment, returning `[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.` error. This is tied to a compatibility issue with `glutin` library, which is resolved in version `0.25`.

You can circumvent the issue by upgrading to `ggez` version `0.16.0-rc0`, which has all the necessary fixes. With one quirk though: on Wayland it produces a window that has no styling. On XOrg everything works, resulting in a normal GNOME-styled window.

I'm not sure this bug needs any fixes on your side per se. Just leaving this here for anyone who stumbles upon a similar issue.

**Comment by iolivia** [comment]
Thanks for this! Need to take a look at the latest ggez releases, we might need to be able to bump the version.

**Comment by iolivia** [comment]
@mister-spock I've upgraded to ggez 0.7, this *should* fix it, but if it doesn't please re-open!
